import { BaseTool } from './base';
import { ToolResult } from '@/agents/types';
import prisma from '@/lib/prisma';

interface ReportSection {
  heading: string;
  content: string;
}

/**
 * PDF Report Generator Tool — creates structured reports stored in the database.
 * The actual PDF rendering happens on the client using @react-pdf/renderer.
 */
export class PDFGeneratorTool extends BaseTool {
  name = 'generate_report';
  description = 'Generate a professional research report with structured sections.';

  private userId: string;
  private chatId: string;

  constructor(userId: string, chatId: string) {
    super();
    this.userId = userId;
    this.chatId = chatId;
  }

  async execute(args: Record<string, unknown>): Promise<ToolResult> {
    const title = args.title as string;
    const sections = args.sections as ReportSection[];
    const summary = args.summary as string;

    if (!title || !sections || !summary) {
      return {
        tool: this.name,
        success: false,
        data: null,
        error: 'Title, sections, and summary are required',
      };
    }

    try {
      // Build full report content as structured markdown
      const reportContent = this.buildReportContent(title, summary, sections);

      // Store report in database
      const report = await prisma.report.create({
        data: {
          userId: this.userId,
          chatId: this.chatId,
          title,
          content: reportContent,
        },
      });

      return {
        tool: this.name,
        success: true,
        data: {
          reportId: report.id,
          title,
          sectionCount: sections.length,
          message: `Report "${title}" has been generated successfully. The user can download it from the Reports page.`,
        },
      };
    } catch (error) {
      return {
        tool: this.name,
        success: false,
        data: null,
        error: error instanceof Error ? error.message : 'Report generation failed',
      };
    }
  }

  private buildReportContent(
    title: string,
    summary: string,
    sections: ReportSection[]
  ): string {
    let content = '';

    content += `# ${title}\n\n`;
    content += `**Generated by MicroManus AI Research Agent**\n`;
    content += `**Date:** ${new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })}\n\n`;
    content += `---\n\n`;
    content += `## Executive Summary\n\n${summary}\n\n`;
    content += `---\n\n`;
    content += `## Table of Contents\n\n`;

    sections.forEach((section, index) => {
      content += `${index + 1}. ${section.heading}\n`;
    });

    content += `\n---\n\n`;

    sections.forEach((section, index) => {
      content += `## ${index + 1}. ${section.heading}\n\n`;
      content += `${section.content}\n\n`;
    });

    content += `---\n\n`;
    content += `*This report was generated by MicroManus AI Research Agent. All information should be verified independently.*\n`;

    return content;
  }

  getParameterSchema(): Record<string, unknown> {
    return {
      type: 'object',
      properties: {
        title: { type: 'string', description: 'Report title' },
        summary: { type: 'string', description: 'Executive summary' },
        sections: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              heading: { type: 'string' },
              content: { type: 'string' },
            },
            required: ['heading', 'content'],
          },
          description: 'Report sections',
        },
      },
      required: ['title', 'sections', 'summary'],
    };
  }
}
